#shallow fnn
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_fnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_d' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_fnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_q' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_fnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='torque' --stride=1 --window=100 --act=relu

#deep fnn
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_fnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_d' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_fnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_q' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_fnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='torque' --stride=1 --window=100 --act=relu


#shallow rnn
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_rnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_d' --stride=1 --window=100 --act=relu --hidden_size=32
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_rnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_q' --stride=1 --window=100 --act=relu --hidden_size=32
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_rnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='torque' --stride=1 --window=100 --act=relu --hidden_size=32

#deep rnn
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_rnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_d' --stride=1 --window=10 --act=relu --hidden_size=32
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_rnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_q' --stride=1 --window=10 --act=relu --hidden_size=32
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_rnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='torque' --stride=1 --window=10 --act=relu --hidden_size=32


#shallow lstm
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_lstm --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_d' --stride=1 --window=100 --act=relu --hidden_size=32
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_lstm --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_q' --stride=1 --window=100 --act=relu --hidden_size=32
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_lstm --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='torque' --stride=1 --window=100 --act=relu --hidden_size=32

#deep lstm
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_lstm --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_d' --stride=1 --window=10 --act=relu --hidden_size=32
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_lstm --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_q' --stride=1 --window=10 --act=relu --hidden_size=32
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_lstm --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='torque' --stride=1 --window=10 --act=relu --hidden_size=32

#shallow cnn
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_cnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_d' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_cnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_q' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_cnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='torque' --stride=1 --window=100 --act=relu

#deep cnn
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_cnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_d' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_cnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_q' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_cnn --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='torque' --stride=1 --window=100 --act=relu

#shallow encdec
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_encdec --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_d' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_encdec --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_q' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=shallow_encdec --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='torque' --stride=1 --window=100 --act=relu

#deep encdec
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_encdec --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_d' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_encdec --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='current_q' --stride=1 --window=100 --act=relu
python3 summoner.py --task=train_sim --train_sim_dir=../../datasets/data/train_sim/ --val_sim_dir=../../datasets/data/val_sim/ --weights_dir=../../weights/ --logs_dir=../../logs/ --model=deep_encdec --epochs=100 --batch_size=1024 --lr=0.01 --inp_quants='voltage_d,voltage_q,speed' --out_quants='torque' --stride=1 --window=100 --act=relu