% load handel
% N = 100;
% y = y(1:N);
torque = load('../../datasets/CS2018_12_14/Torque.mat');
y = torque.Torque;

% N = 512;
% y = zeros(N,1);
% y(50:80,1) = sin((50:80)*pi/4).*(hamming(31))';
% y = y + 0.05*randn(size(y));

%N = length(y);
%K = 32; % number of subbands
L = 128; % filter length
%dcttype = 4;

% perform subband decomposition
c = analDCTFB(y,L); % coefficients generated by subband decomposition
%c = analDCTFB(y,L,K);
%c = analDCTFB(y,L,K,dcttype);

imagesc(flipud(c)) % plots coefficients like a spectrogram representation

% perform signal reconstruction 
yr = synthDCTFB(c);
%yr = synthDCTFB(c,L);
%yr = synthDCTFB(c,L,dcttype);

%disp('reconstruction error = %g',num2str(norm(y-yr)))
fprintf(1,'reconstruction error = %g\n',norm(y-yr))
    
    
